version: "3.8"

services:
  mongo-poc-node-1:
    image: poc/mongo:6.0.6
    container_name: mongo-poc-node-1
    build:
      context: ./MongoDB/
      dockerfile: Dockerfile
    command: mongod --port 30001 --bind_ip_all --replSet mrs --keyFile /data/mongodb-keyfile
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${PWD}
    volumes:
      - mongo-poc-node-1-data:/data/db
      - mongo-poc-node-1-config:/data/configdb
    networks:
      - default
    ports:
      - 30001:30001

  mongo-poc-node-2:
    image: poc/mongo:6.0.6
    container_name: mongo-poc-node-2
    build:
      context: ./MongoDB/
      dockerfile: Dockerfile
    command: mongod --port 30002 --bind_ip_all --replSet mrs --keyFile /data/mongodb-keyfile
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${PWD}
    volumes:
      - mongo-poc-node-2-data:/data/db
      - mongo-poc-node-2-config:/data/configdb
    networks:
      - default
    ports:
      - 30002:30002

  mongo-poc-node-3:
    image: poc/mongo:6.0.6
    container_name: mongo-poc-node-3
    build:
      context: ./MongoDB/
      dockerfile: Dockerfile
    command: mongod --port 30003 --bind_ip_all --replSet mrs --keyFile /data/mongodb-keyfile
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${PWD}
    volumes:
      - mongo-poc-node-3-data:/data/db
      - mongo-poc-node-3-config:/data/configdb
    networks:
      - default
    ports:
      - 30003:30003

volumes:
  mongo-poc-node-1-data:
  mongo-poc-node-1-config:

  mongo-poc-node-2-data:
  mongo-poc-node-2-config:

  mongo-poc-node-3-data:
  mongo-poc-node-3-config:

networks:
  default:
    name: mongo_poc_rs
