version: "3.8"

services:
  node-1:
    image: poc/mongo:6.0.6
    build:
      context: ./MongoDB/
      dockerfile: Dockerfile
    command: mongod --config /data/conf/mongod.conf --port 30001
    extra_hosts:
      - "mongo-poc:host-gateway"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${PWD}
    volumes:
      - node-1-data:/data/db
      - node-1-config:/data/configdb
    networks:
      - default
    ports:
      - 30001:30001

  node-2:
    image: poc/mongo:6.0.6
    build:
      context: ./MongoDB/
      dockerfile: Dockerfile
    command: mongod --config /data/conf/mongod.conf --port 30002
    extra_hosts:
      - "mongo-poc:host-gateway"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${PWD}
    volumes:
      - node-2-data:/data/db
      - node-2-config:/data/configdb
    networks:
      - default
    ports:
      - 30002:30002

  node-3:
    image: poc/mongo:6.0.6
    build:
      context: ./MongoDB/
      dockerfile: Dockerfile
    command: mongod --config /data/conf/mongod.conf --port 30003
    extra_hosts:
      - "mongo-poc:host-gateway"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${PWD}
    volumes:
      - node-3-data:/data/db
      - node-3-config:/data/configdb
    networks:
      - default
    ports:
      - 30003:30003

volumes:
  node-1-data:
  node-1-config:

  node-2-data:
  node-2-config:

  node-3-data:
  node-3-config:

networks:
  default:
    name: mongo_poc_rs
